### ISSUE TITLE
KVM websocket connection is leaking

### ISSUE THREAD

**Issue by LeeTroy** [openbmc/webui-vue#61] opened 2021-05-06 10:15 UTC
**Describe the bug**
Click on refresh button when launch KVM, the old websocket session will keep alive but create a new one. Click multiple times will raise Max Session issue.

**To Reproduce**
1. Go to 'Control' -> 'KVM'
2. Click on 'Refresh' with four times
3. See KVM disconnection error

**Expected behavior**
Either the old websocket session should be reuse or close the old session and create another new session.

**Screenshots**
![KVM-Max-Session](https://user-images.githubusercontent.com/714702/117282063-ea0d4e00-ae96-11eb-8632-62ff8f452d10.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 90

**Comment by LeeTroy** [comment] 2021-05-07 01:17
Exactly. Even though the KVM status shows disconnected, the underlying 4 websockets are still transmitting the video frames.

When I click on refresh button, the button will emit a `refresh` event.
https://github.com/openbmc/webui-vue/blob/f3022e5c1ad1f4d83d03d996d77094a87f4be8e0/src/components/AppHeader/AppHeader.vue#L205-L207

But KvmConsole.vue doesn't listen and handle the event.
https://github.com/openbmc/webui-vue/blob/15bcc41f748a79201eebd46496256621870a527e/src/views/Control/Kvm/KvmConsole.vue#L102-L129

**Comment by derick-montague** [comment] 2021-05-27 22:06
Thank you for uncovering and sharing this bug. I have added it to the help wanted Project. I believe that Intel is using the feature. I will add it to the next design work group meeting agenda if someone doesn't pick it up before then. @mszopinx or @mmagdzix - Have either of you experienced this issue?

**Comment by leiyu-bytedance** [comment] 2021-06-16 05:19
We hit exactly the same issue.
It looks like the webui should either re-use the WebSocket, or close it when the page is refreshed or goes out of the KVM page.

**Comment by mmagdzix** [comment] 2021-06-23 12:16
> Thank you for uncovering and sharing this bug. I have added it to the help wanted Project. I believe that Intel is using the feature. I will add it to the next [design work group meeting agenda](https://github.com/openbmc/openbmc/wiki/GUI-Design-work-group) if someone doesn't pick it up before then. @mszopinx or @mmagdzix - Have either of you experienced this issue?

@derick-montague We could reproduce this issue and working on fixing it.

**Comment by mmagdzix** [comment] 2021-06-23 15:35
Sorry I missed that fixed is was already prepared. I have reviewed it and tested.

**Comment by derick-montague** [comment] 2021-06-23 15:48
Resolved by: https://gerrit.openbmc-project.xyz/c/openbmc/webui-vue/+/44223

**Closed** 2021-06-23 15:49 UTC
Labels: bug
