### ISSUE TITLE
meta-phosphor/recipes-phosphor/webui/nlf_2.1.1.bb no longer bulds with latest yocto

### ISSUE THREAD

**Issue by geissonator** [openbmc/webui-vue#92] opened 2022-01-24 16:15 UTC
**Describe the bug**
webui-vue does not build any longer with the latest upstream yocto rebase

The error is the following:
```
npm verb stack Error: request to https://registry.npmjs.org/archy failed: cache mode is 'only-if-cached' but no cached response is available.
```

**To Reproduce**
1. Build code with latest yocto subtree updates - https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/48473/

**Expected behavior**
Code should build

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Revert is here: https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/50137

Will need to do this to move forward with yocto rebases.

**Comment by jorgecis** [comment] 2022-02-08 00:34
I have a problem compiling WebUI with the last yocto, the problem is a new security feature, to fix my issue I modified the recipe 

`devtool modify webui-vue
`

to add this line.

`do_compile[network] = "1"
`

**Comment by gtmills** [comment] 2024-04-29 16:09
@geissonator Still a problem or can this be closed?

**Comment by geissonator** [comment] 2024-04-29 16:16
> @geissonator Still a problem or can this be closed?

Doesn't look like https://gerrit.openbmc.org/c/openbmc/openbmc/+/50137 ever go un-reverted so yeah I assume we've still got it. But the fact it's been reverted for so long implies it wasn't needed. So I'm fine if you just want to close this one out as a permanent restriction.

**Comment by gtmills** [comment] 2024-04-29 16:21
Closing. Thanks Andrew.

**Closed as completed by gtmills** 2024-04-29 16:21 UTC
